### PR TITLE
Fix a spelling mistake in the help message.

### PR DESCRIPTION
**Pull request by yoichiro**
I found a spelling mistake in the help message. Could you review this pull request and merge it?
Thank you!

### CODE REVIEW

**Review by taiki45 — COMMENTED** [review]
Thanks for sending the PR.

Cloud you remove adding test code? I don't think the test is useful.

**Comment by yoichiro** [comment]
@taiki45 I just removed the test code I added. Could you review this again?

**Comment by taiki45** [comment]
Thanks!

**Comment by taiki45** [comment]
Released as v0.1.1.

**Pull request merged**
